// <auto-generated />
using System;
using HookedUp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HookedUp.Migrations
{
    [DbContext(typeof(HookedUpDbContext))]
    [Migration("20250603022036_FixForeignKeyDirectMessage")]
    partial class FixForeignKeyDirectMessage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HookedUp.Models.ArtistProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ExpertiseLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("WorkDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("WorkImages")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("ArtistProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 6, 2, 21, 20, 36, 272, DateTimeKind.Local).AddTicks(5422),
                            ExpertiseLevel = "Advanced",
                            ProfilePicture = "https://example.com/artist1.jpg",
                            Specialization = "Crochet",
                            UpdatedAt = new DateTime(2025, 6, 2, 21, 20, 36, 272, DateTimeKind.Local).AddTicks(5538),
                            UserId = 2,
                            WorkDescription = "Experienced in creating custom crochet items.",
                            WorkImages = new[] { "https://example.com/work1.jpg", "https://example.com/work2.jpg" }
                        });
                });

            modelBuilder.Entity("HookedUp.Models.DirectMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProjectRequestId")
                        .HasColumnType("integer");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProjectRequestId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("DirectMessages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MessageText = "Hi, I'd love to help with your baby blanket project!",
                            ProjectRequestId = 1,
                            ReceiverId = 2,
                            SenderId = 1,
                            Timestamp = new DateTime(2025, 6, 2, 21, 20, 36, 273, DateTimeKind.Local).AddTicks(1643)
                        });
                });

            modelBuilder.Entity("HookedUp.Models.ProjectRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Claimed")
                        .HasColumnType("boolean");

                    b.Property<int?>("ClaimedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProjectType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ProjectRequests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Claimed = false,
                            CreatedAt = new DateTime(2025, 6, 2, 21, 20, 36, 272, DateTimeKind.Local).AddTicks(8199),
                            Description = "Need a crocheted baby blanket.",
                            DueDate = new DateTime(2025, 6, 7, 21, 20, 36, 272, DateTimeKind.Local).AddTicks(7772),
                            Location = "New York",
                            ProjectType = "Crochet",
                            Status = "Open",
                            Title = "Create a Baby Blanket",
                            UpdatedAt = new DateTime(2025, 6, 2, 21, 20, 36, 272, DateTimeKind.Local).AddTicks(8278),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("HookedUp.Models.ReviewRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("ProjectRequestId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string[]>("ReviewImage")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ReviewText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ReviewRatings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistId = 2,
                            CreatedAt = new DateTime(2025, 6, 2, 21, 20, 36, 273, DateTimeKind.Local).AddTicks(85),
                            ProjectRequestId = 1,
                            Rating = 5,
                            ReviewImage = new[] { "https://example.com/reviewimage1.jpg" },
                            ReviewText = "Amazing crochet work! Very satisfied.",
                            UpdatedAt = new DateTime(2025, 6, 2, 21, 20, 36, 273, DateTimeKind.Local).AddTicks(185),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("HookedUp.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePicture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 6, 2, 21, 20, 36, 270, DateTimeKind.Local).AddTicks(4980),
                            Email = "sirenafoster@example.com",
                            Name = "Sirena Foster",
                            Password = "password123",
                            ProfilePicture = "https://example.com/sirenafoster.jpg",
                            Role = "user",
                            UpdatedAt = new DateTime(2025, 6, 2, 21, 20, 36, 272, DateTimeKind.Local).AddTicks(74)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 6, 2, 21, 20, 36, 272, DateTimeKind.Local).AddTicks(252),
                            Email = "jane.smith@example.com",
                            Name = "Jane Smith",
                            Password = "password456",
                            ProfilePicture = "https://example.com/janesmith.jpg",
                            Role = "artist",
                            UpdatedAt = new DateTime(2025, 6, 2, 21, 20, 36, 272, DateTimeKind.Local).AddTicks(257)
                        });
                });

            modelBuilder.Entity("HookedUp.Models.DirectMessage", b =>
                {
                    b.HasOne("HookedUp.Models.ProjectRequest", "ProjectRequest")
                        .WithMany()
                        .HasForeignKey("ProjectRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HookedUp.Models.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HookedUp.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectRequest");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });
#pragma warning restore 612, 618
        }
    }
}
